---
version: "3.7"

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
      - 8080:8080
    environment:
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=ssm,dynamodb,ses,s3
    logging:
      options:
        max-size: "5mb"
        max-file: "3"
